### ISSUE TITLE
sudo su doesn't work

### ISSUE THREAD

**Issue by erayrafet** [openFyde/overlay-amd64-openfyde_iris#2]
As stated in the Releases page with the commands to install Borealis, `sudo su` isn't compatible and throws an error. `sudo -i` works.

**Comment by DarkevilPT** [comment]
LaCros also doesnt work anymore.
Steam via borealis cant be installed due to sudo -i changed.
Most wifi modules are not installed in kernel or have compatability issues...
Fyde has plenty of work in hands to do..

**Comment by erayrafet** [comment]
![image](https://github.com/openFyde/overlay-amd64-openfyde_iris/assets/34194191/8904c8d5-7e0e-49a0-a6ff-99e4b08fd69b)
No wifi or bt with my trl8822be.
