### ISSUE TITLE
13th gen i7-1355u not booting

### ISSUE THREAD

**Issue by skiv71** [openFyde/overlay-amd64-openfyde_iris#4]
Hi,

I currently use FydeOS 17.1 iris and fancied trying OF, but neither the USB or the manually written image to disk (via the install script) will boot.

I see Fyde is using the same 114 core, so should work?

Thanks

Skiv

**Comment by JUJODEMULA1** [comment]
Ami tampoco en intel 12 generacion
Con gráficos iris estoy probando grabarla en varios usb y de direrente manera

**Comment by Lorde627** [comment]
13th generation processors are not supported at this time.
