### ISSUE TITLE
OpenFyde not boot

### ISSUE THREAD

**Issue by bybenjamin** [openFyde/overlay-amd64-openfyde_iris#6]
My laptop, which has a 12th generation i5-1235U processor and Intel Iris xe graphics card, does not boot in openfyde.
Fydeos is fine too. Only on openfyde.
Since we cannot enable verbose mode, we cannot diagnose where the problem is coming from.

**Comment by Lorde627** [comment]
Please try using the latest version r120 to see if it can solve the problem.
